name: Job - Format SQL

on:
  workflow_call:

jobs:
  format:
    runs-on: ubuntu-slim
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref }}
      - uses: quarylabs/install-sqruff-cli-action@7805329baf7cf340e849e254cddc782f08f2d36c # master
      - name: Apply format
        run: sqruff fix . --format github-annotation-native
      - name: Check for changes
        id: diff
        run: git diff --quiet || echo "changed=true" >> $GITHUB_OUTPUT
        shell: bash
      - name: Commit changes
        if: steps.diff.outputs.changed == 'true'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add *.sql
          git commit -m "Apply format SQL files"
          git push
        shell: bash
